### ISSUE TITLE
Question: How to detroy the stack

### ISSUE THREAD

**Issue by shokinn** [kdybicz/dispose-me#7]
Hey,
I would like to know if there is an easy way to destroy the stack?
Or do I have to delete/destroy everything manually?

**Comment by kdybicz** [comment]
try with `npx sls remove --stage production` or https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stackinstances-delete.html

**Comment by shokinn** [comment]
Works fine!
Thank you!
