### ISSUE TITLE
Feature request: Backlisting email adresses

### ISSUE THREAD

**Issue by shokinn** [kdybicz/dispose-me#8]
Since I would like to make my dispose me instance public, I would like to see a kind of blacklist for emails.
At best it would be a list with wildcards org regex configurable.

**Comment by kdybicz** [comment]
@shokinndo That would be doable, though I'm not sure what would be the benefit of having it in place? There are two things to note:
1. Even if the API and web are key protected, anyone can send you an email as this part doesn't require any authentication.
2. Regardless if such filtering would be on or off it would still trigger Lambda processing the email payload to determine if it should be processed further.

What's the end goal you're trying to achieve?

**Comment by shokinn** [comment]
Hey,
the benefit would be to blacklist addresses like hostmaster@, postmaster@, webmaster@, admin@, administrator@, ...
These addresses can be quiet destructive since maybe someone can try to steal the domain.

This would particular threatening, when you make your dispose me instance public (#9).

**Comment by kdybicz** [comment]
@shokinn Thanks! That's something I didn't took into consideration since now. I'm wondering if it would make more sense redirect such emails to real email of the service owner rather than just dropping 🤔

**Comment by shokinn** [comment]
Ideal would be to be able to configure this 🙂.
Even better to be able to to this for each email.
Maybe two arrays out of regex patterns (one for dropping, one for forwarding)?

**Comment by kdybicz** [comment]
@shokinn sorry it take soo long, would you like to take a look at #13 and share some fedback?
